modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="lumenized"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile="logo.png"
description='''${mod_description}'''
mixinConfigs="${mod_id}.mixins.json"

[[dependencies.lumenized]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.lumenized]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

